openapi: 3.0.0
info:
  title: Book API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /book:
    get:
      summary: Get a list of books
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
      responses:
        201:
          description: Created
    put:
      summary: Update an existing book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                author:
                  type: string
      responses:
        200:
          description: Success
    delete:
      summary: Delete a book
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: The id of the book to delete
      responses:
        200:
          description: Success
